---
abstract: ~
author:
  - 'Logan Bell, C<< <loganbell at gmail.com> >>'
  - 'Logan Bell <loganbell@gmail.com>'
build_requires:
  DBIx::Class::TimeStamp: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-IndexSearch-Dezi
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  DBIx::Class: 0
  Module::Load: 0
  Moo: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
